export enum StatusType {
    PURPLE_SHIELD = 'PURPLE_SHIELD',
    YELLOW_SHIELD = 'YELLOW_SHIELD',
    DROPPING_PUDDLES = 'DROPPING_PUDDLES',
    SIMPLE_COUNTDOWN = 'SIMPLE_COUNTDOWN',
    RED_SHIELD = 'RED_SHIELD',
    BLUE_SHIELD = 'BLUE_SHIELD'
}